spring.application.name=Odito

# Server
server.port=8081

# Base metier odito
spring.datasource.url=jdbc:postgresql://localhost:5432/odito
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =====================================================
# Configuration Squelette Auth (base partagee gesta_auth)
# =====================================================
squelette.datasource.url=jdbc:postgresql://localhost:5432/gesta_auth
squelette.datasource.username=postgres
squelette.datasource.password=admin

# JWT Configuration (meme secret que materio = SSO)
squelette.jwt.secret=PnF+n/wsQBdWcW8m8+vDU+H9xzAaV2bwPcxU54/aR8jVXdh6RbW3vx/i4wkZTdHAc8L+UgmWPHjvI15Mqm7LVw==
squelette.jwt.issuer=gesta

# Security Configuration
squelette.security.public-endpoints=/auth/**,/api/v1/templates/public/**
squelette.security.allowed-origins=http://localhost:3000,http://localhost:5173

# Logging
logging.level.com.odito=DEBUG
logging.level.org.springframework.web=DEBUG
